on: [push]

name: DeployWebAppIAC 

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          terraform 
        sparse-checkout-cone-mode: false

    - run: cd terraform

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init

    - id: plan
      run: terraform plan -no-color

    - run: echo ${{ steps.plan.outputs.stdout }}
    - run: echo ${{ steps.plan.outputs.stderr }}
    - run: echo ${{ steps.plan.outputs.exitcode }}
